### ISSUE TITLE
every sam so far causes exception

### ISSUE THREAD

**Issue by colindaven** [t-ogasawara/sam-to-bam#2]
wget https://raw.githubusercontent.com/samtools/samtools/develop/examples/toy.sam

build/samtools/samtools sam2bam -oout_fast.bam   toy.sam

(I) #physical_cores 6
(I) sam-to-bam $Rev: 85 $
(I) **** built with no DEBUG_POS feature
(I) dict_rg2lib count 0
(I) use_nproc 12 hts_proc_offset 3 hts_nproc 11
(I) #read 1 #split 1 #parse 1 #copy 1 #hash 1
(I) #mate 10 #sort 12
(I) memory mode: no external paging
(I) setaffinity in the gzip-and-write stage disabled (always in x86_64)
(I) CPU            zlib  -- -o oo -o oo oo -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU      bam_writer  -- -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
`Floating point exception (core dumped)`

Also with a tiny sub sampled STAR aligned RNA-seq file (can supply if necessary)

build/samtools/samtools sam2bam -oout_fast.bam   test2000lines.sam
(I) #physical_cores 6
(I) sam-to-bam $Rev: 85 $
(I) **** built with no DEBUG_POS feature
(I) dict_rg2lib count 0
(I) use_nproc 12 hts_proc_offset 3 hts_nproc 11
(I) #read 1 #split 1 #parse 1 #copy 1 #hash 1
(I) #mate 10 #sort 12
(I) memory mode: no external paging
(I) setaffinity in the gzip-and-write stage disabled (always in x86_64)
(I) CPU            zlib  -- -o oo -o oo oo -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU      bam_writer  -- -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Floating point exception (core dumped)

Also on a full sized STAR aligned RNA-seq SAM file

build/samtools/samtools sam2bam -oout_fast.bam   test.sam 
(I) #physical_cores 6
(I) sam-to-bam $Rev: 85 $
(I) **** built with no DEBUG_POS feature
(I) dict_rg2lib count 0
(I) use_nproc 12 hts_proc_offset 3 hts_nproc 11
(I) #read 1 #split 1 #parse 1 #copy 1 #hash 1
(I) #mate 10 #sort 12
(I) memory mode: no external paging
(I) setaffinity in the gzip-and-write stage disabled (always in x86_64)
(I) CPU            zlib  -- -o oo -o oo oo -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU      bam_writer  -- -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Floating point exception (core dumped)

And lastly - trying sort with a full BAM file

build/samtools/samtools sam2bam -Fsort_by_coordinate: -oout_fast.bam test.sam
(I) filter sort_by_coordinate args 
(I) #physical_cores 6
(I) sam-to-bam $Rev: 85 $
(I) **** built with no DEBUG_POS feature
(I) dict_rg2lib count 0
(I) FILTER: /mnt/NAS01/bioinformatics/programs/sam2bam/build/samtools/filter.d/lib_sort_by_coordinate.so
(I) /mnt/NAS01/bioinformatics/programs/sam2bam/build/samtools/filter.d/lib_sort_by_coordinate.so provides no pre_filter
(I) /mnt/NAS01/bioinformatics/programs/sam2bam/build/samtools/filter.d/lib_sort_by_coordinate.so provides no post_filter
(I) /mnt/NAS01/bioinformatics/programs/sam2bam/build/samtools/filter.d/lib_sort_by_coordinate.so provides no analyze_data
(I) supported API version: 1
(I) lib_sort_by_coordinate.so init_filter() succeeded and provides "sort_by_coordinate" filter
(I) #read 1 #split 1 #parse 1 #copy 1 #hash 1
(I) #mate 10 #sort 12
(I) memory mode: no external paging
(I) CPU      db_builder  -- -- o- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU        bam_virt  -- -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU      sam_parser  -- o- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU   line_splitter  -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU    block_reader  o- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) read naming convention: Illumina 1.8
`(E) clip length 45791 cannot be expressed in 16 bits. 11775708 DE18INS60513:213:CA5VCANXX:8:1115:2022:37489 83 2 11664381`

Any ideas ? Is my installation even valid ? Do you have a test sam on a webserver somewhere ?

cheers

**Comment by t-ogasawara** [comment]
@colindaven Thank you for your issue report. The first three issues will be fixed on the latest code, but I don't know that it works for the last issue. If you still observe the last issue, could you open a separate issue with a small dataset?
