### ISSUE TITLE
SAM issues

### ISSUE THREAD

**Issue by colindaven** [t-ogasawara/sam-to-bam#3]
Hi,

thanks for the prompt fixes - I got the new code. I can run toy.sam through now.

https://drive.google.com/open?id=0B-ZVOKUcgOHROV85WExtaGtiZkU

Here are another few small SAM examples which do not run.

One, test_springer.sam, causes "- ID too large exception" or similar. It is important these work since they are from the popular NCBI SRA DB.

The other, test_2000.sam, causes a floating point exception.

**Comment by t-ogasawara** [comment]
@colindaven Thank you for your providing small SAM examples. I downloaded them. I would like to reproduce what you are observing (sam2bam finished with no problems in my environment).

The issue could depend on environments. Could you copy outputs from (1) lscpu and (2) lsb_release -a? I will find a machine that has a similar configuration and try the test on it.

**Comment by colindaven** [comment]
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             3
NUMA node(s):          3
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Stepping:              2
CPU MHz:               2900.000
BogoMIPS:              5800.00
Virtualization:        VT-x
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-11
NUMA node1 CPU(s):     
NUMA node2 CPU(s): 

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty


In more detail:

~/NAS01/programs/sam2bam/build/samtools/samtools sam2bam -oout_fast.bam   test_2000.sam 
(I) #physical_cores 6
(I) sam-to-bam $Rev: 86 $
(I) **** built with no DEBUG_POS feature
(I) dict_rg2lib count 0
(I) use_nproc 12 hts_proc_offset 3 hts_nproc 11
(I) #read 1 #split 1 #parse 1 #copy 1 #hash 1
(I) #mate 10 #sort 12
(I) memory mode: no external paging
(I) setaffinity in the gzip-and-write stage disabled (always in x86_64)
(I) CPU            zlib  -- -o oo -o oo oo -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU      bam_writer  -- -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Floating point exception (core dumped)


~/NAS01/programs/sam2bam/build/samtools/samtools sam2bam -oout_fast.bam   test_springer.sam 
(I) #physical_cores 6
(I) sam-to-bam $Rev: 86 $
(I) **** built with no DEBUG_POS feature
(I) dict_rg2lib count 0
(I) use_nproc 12 hts_proc_offset 3 hts_nproc 11
(I) #read 1 #split 1 #parse 1 #copy 1 #hash 1
(I) #mate 10 #sort 12
(I) memory mode: no external paging
(I) setaffinity in the gzip-and-write stage disabled (always in x86_64)
(I) CPU            zlib  -- -o oo -o oo oo -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU      bam_writer  -- -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Floating point exception (core dumped)





So like you say, it might be the VM environment. I have a physical server with Ubuntu 14.04 too, and tried this. This a) succeeds at sam2bam -- great !  but b) still gets a floating point exception with sorting.

lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Stepping:              4
CPU MHz:               2600.203
BogoMIPS:              5204.72
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,32-39
NUMA node1 CPU(s):     8-15,40-47
NUMA node2 CPU(s):     16-23,48-55
NUMA node3 CPU(s):     24-31,56-63



lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty



~/NAS01/programs/sam2bam/build/samtools/samtools sam2bam -oout_fast22.bam test_2000.sam (I) #physical_cores 32
(I) sam-to-bam $Rev: 86 $
(I) **** built with no DEBUG_POS feature
(I) dict_rg2lib count 0
(I) use_nproc 64 hts_proc_offset 16 hts_nproc 50
(I) #read 1 #split 1 #parse 1 #copy 1 #hash 1
(I) #mate 56 #sort 64
(I) memory mode: no external paging
(I) setaffinity in the gzip-and-write stage disabled (always in x86_64)
(I) CPU            zlib  -- -- -- -- -- -- -- -- oo oo oo oo oo oo oo oo -o oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo
(I) CPU      bam_writer  -- -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU      sam_parser  -- o- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU   line_splitter  -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU    block_reader  o- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) 0                       50                      100 %
(I) +----+----+----+----+----+----+----+----+----+----+
(I)  ################################################## 100 % 0 MB 0.0 MB/s
(I) 0                       50                      100 % (wr)
(I) +----+----+----+----+----+----+----+----+----+----+ (wr)
(I)  ################################################## 100 % 0 MB 0.0 MB/sec (0 to be deflated 0 being deflated)
[    2.48] read finished (0.3 MB/s)  (open time 0.0 sec count 1)
(I) CPU            zlib  -- oo oo oo oo oo oo o- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
[    2.49] sam-to-bam finished
[    3.48] process finished (1.0 s for closing the output file)



~/NAS01/programs/sam2bam/build/samtools/samtools sam2bam -Fsort_by_coordinate: -oout_fast.bam test_2000.sam

(W) HWI-ST1006:215:C68MBACXX::2216:89537:2201:38165:11314 (qnameid 3875141635819449394) is paired (shown in FLAG) but has no pair read in inputs (flag 99)
(W) HWI-ST1006:215:C68MBACXX::1303:38357:1307:34377:80358 (qnameid 3875110914240887270) is paired (shown in FLAG) but has no pair read in inputs (flag 99)
(W) HWI-ST1006:215:C68MBACXX::1303:38357:1215:42118:35838 (qnameid 3875107761262463998) is paired (shown in FLAG) but has no pair read in inputs (flag 99)
[    1.16] find mates finished (0.1 sec)
[    1.16] sort_by_coordinate started...
[    1.16] sort_by_coordinate finished (0.0 sec)
(I) setaffinity in the gzip-and-write stage disabled (always in x86_64)
(I) CPU            zlib  -o oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo -o oo oo oo oo oo oo oo oo oo oo oo oo oo oo oo
write index range: 4096 - 4096
[    1.55] BGZF request finished (0.0 MB/s)
(I) 0                       50                      100 % (wr)
(I) +----+----+----+----+----+----+----+----+----+----+ (wr)
(I)  .................................................. (wr)
Floating point exception (core dumped)

**Comment by t-ogasawara** [comment]
Sorry for the delay until I can start to debug this issue because of other high-priority issues/features.

I fixed problems for test_springer.sam. Can you check again?

I do not fix problems for test_2000.sam yet. I reopen this.
