### ISSUE TITLE
too large accession number

### ISSUE THREAD

**Issue by colindaven** [t-ogasawara/sam-to-bam#4]
This was on the physical server with the file test_springer.sam

sam2bam works fine, great.

However an error occurs with the read naming conventions. This is public data from the NCBI SRA.

Hope that helps.

sam2bam -oout_fast22.bam -Fsort_by_coordinate: test_springer.sam 
(I) filter sort_by_coordinate args 
(I) #physical_cores 32
(I) sam-to-bam $Rev: 86 $
(I) **** built with no DEBUG_POS feature
(I) dict_rg2lib count 0
(I) FILTER: /mnt/NAS01/bioinformatics/programs/sam2bam/build/samtools/filter.d/lib_sort_by_coordinate.so
(I) /mnt/NAS01/bioinformatics/programs/sam2bam/build/samtools/filter.d/lib_sort_by_coordinate.so provides no pre_filter
(I) /mnt/NAS01/bioinformatics/programs/sam2bam/build/samtools/filter.d/lib_sort_by_coordinate.so provides no post_filter
(I) /mnt/NAS01/bioinformatics/programs/sam2bam/build/samtools/filter.d/lib_sort_by_coordinate.so provides no analyze_data
(I) supported API version: 1
(I) lib_sort_by_coordinate.so init_filter() succeeded and provides "sort_by_coordinate" filter
(I) #read 1 #split 1 #parse 1 #copy 1 #hash 1
(I) #mate 56 #sort 64
(I) memory mode: no external paging
(I) CPU      db_builder  -- -- o- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU        bam_virt  -- -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU      sam_parser  -- o- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU   line_splitter  -o -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) CPU    block_reader  o- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
(I) read naming convention: SRR
(E) ** too large accession number: SRR1819622.14270392

**Comment by t-ogasawara** [comment]
@colindaven Let me think about how to fix this issue. Do you have the information of how many digits can be used for fields A and B for "SRR"<A>"."<B>?

**Comment by colindaven** [comment]
Sure, no problem, happy to help test.

As far as I know currently part A (SRR) is always 10 characters including the SRR.

Part B is just the current read number, starting from 1 (see below). There is therefore absolutely no way to know how many characters or digits to expect here.

Example: input fastq

@SRR1663691.1 1 length=51
GAAGCCCGAGGTGAAGAGCATCCAGATCTCCGGCTGAAGAAGACATGGACG
+SRR1663691.1 1 length=51
CCCFFFFFFHHCFGIGIIJIIJJJJIJGHIJIJJJJEHJIIGJIIHIIIII
@SRR1663691.2 2 length=51
CGGCTACCCTGGCGGCGGCCGCGGCGGTTACTGCAGGTGGGGGTGCTGCAA
+SRR1663691.2 2 length=51
CCCFFFFFHHHHGHIGJJJJHHBBBBD7@BCC@C@CD8ABDDD07?ACCDD
@SRR1663691.3 3 length=51
CTAANACAGAAGACCAACAAGAAGCCAGAGATATCAGCTTGCAGGTACAAG
+SRR1663691.3 3 length=51
@@@D#2=2AFDDFFIIIIIFI@BCGEDGFBFEFFDGI><FGIADA8BFFCF

**Comment by t-ogasawara** [comment]
The last commit fixed this problem.
